---
neovim_version: "0.10.3"
nerdfonts_version: "3.0.2"
neovim_plugin_path: "~/.local/share/nvim/site/pack/plugins/start"
neovim_dir:
  - "{{ neovim_plugin_path }}"
  - "~/.config/nvim"
  - "~/.config/sqls"
  - "/usr/local/src/nvim"
  - "~/.claude"
neovim_plugins:
  - name: "airblade/vim-gitgutter"
    version: "00df1089b6267f47c7c0f13536789feb9db1e65b"
  - name: "junegunn/fzf"
    version: "46877e0a92d5e18bfc143ac98bb55b22eaef81ac"
  # fzf-preview.vim のバージョンは暫くこのコミットで固定
  # 最新コミットにしたら何故か動かなくなった為
  - name: "yuki-yano/fzf-preview.vim"
    version: "fb268bb248a83165abcc75509832f93be9741b3b"
  - name: "lambdalisue/fern.vim"
    version: "41710c31fffa76d08b8cfcd53d5defa7c07a3fc6"
  - name: "lambdalisue/fern-git-status.vim"
    version: "151336335d3b6975153dad77e60049ca7111da8e"
  # SQL 関連
  - name: "sqls-server/sqls"
    version: "eb695acda8a928f6633555fedb91b22e6290f0f0"
  - name: "nanotee/sqls.nvim"
    version: "a514379f5f89bf72955ed3bf5c1c31a40b8a1472"
  - name: "mattn/vim-sqlfmt"
    version: "db6365103e38d274efe7689a002646a4419ae821"
  # ディレクトリ移動
  - name: "mattn/vim-findroot"
    version: "76af2f097cf8196b00f049054444966d10c82f95"
  # claude code
  - name: "greggh/claude-code.nvim"
    version: "ffdf35d8566528cb144d9812eccfecee34502edf"
  - name: "nvim-lua/plenary.nvim"
    version: "857c5ac632080dba10aae49dba902ce3abf91b35"
  # カラースキーマ
  - name: "morhetz/gruvbox"
    version: "bf2885a95efdad7bd5e4794dd0213917770d79b7"
  # NerdFont 関連
  - name: "lambdalisue/nerdfont.vim"
    version: "85dcc800c94f7ab04e13900d6668faf86a0cdc78"
  - name: "lambdalisue/fern-renderer-nerdfont.vim"
    version: "1e90a78ab5510fbcedc85abeb9a251d978726935"
  # その他
  - name: "neovim/nvim-lspconfig"
    version: "v1.2.0"
  - name: "tpope/vim-fugitive"
    version: "5b0b138483de17a8fd8dfcec0b491782c8fbf102"
  - name: "vim-airline/vim-airline"
    version: "9e2d021fc6088a2027315d7e7ae8bafa94f16a7d"
  - name: "vim-airline/vim-airline-themes"
    version: "dd81554c2231e438f6d0e8056ea38fd0e80ac02a"
  - name: "thinca/vim-qfreplace"
    version: "db1c4b0161931c9a63942f4f562a0d0f4271ac14"
  # 以降は nvim-cmp (補完関連) のプラグイン
  - name: "hrsh7th/cmp-nvim-lsp"
    version: "59224771f91b86d1de12570b4070fe4ad7cd1eeb"
  - name: "hrsh7th/cmp-buffer"
    version: "3022dbc9166796b644a841a02de8dd1cc1d311fa"
  - name: "hrsh7th/cmp-path"
    version: "91ff86cd9c29299a64f968ebb45846c485725f23"
  - name: "hrsh7th/cmp-cmdline"
    version: "23c51b2a3c00f6abc4e922dbd7c3b9aca6992063"
  - name: "hrsh7th/nvim-cmp"
    version: "d09b0c396aaa078cdfe78316ec06940971136e85"
  - name: "hrsh7th/cmp-vsnip"
    version: "989a8a73c44e926199bfd05fa7a516d51f2d2752"
  - name: "hrsh7th/vim-vsnip"
    version: "8dde8c0ef10bb1afdbb301e2bd7eb1c153dd558e"
  - name: "L3MON4D3/LuaSnip"
    version: "5570fd797eae0790affb54ea669a150cad76db5d"
  - name: "saadparwaiz1/cmp_luasnip"
    version: "18095520391186d634a0045dacaa346291096566"
  - name: "SirVer/ultisnips"
    version: "e99fdf15cd55a4a8e0cb0a80a6810c1867a5c401"
  - name: "quangnguyen30192/cmp-nvim-ultisnips"
    version: "21f02b62deb409ce69928a23406076bd0043ddbc"
  - name: "dcampos/nvim-snippy"
    version: "47def62945611212a242657cc414dac91ca0453a"
  - name: "dcampos/cmp-snippy"
    version: "9af1635fe40385ffa3dabf322039cb5ae1fd7d35"
db_user: "root"
db_password: ""
db_dbname: "mysql"

