---
common_pkg:
  - gh
  - git
  - git-lfs
  - graphviz
  - htop
  - jq
  - pwgen
  - redis
  - ripgrep
  - tree
  - unzip
apt_pkg:
  - default-jre
  - dotnet-sdk-6.0
  - g++
  - language-pack-ja
  - language-pack-ja-base
  - libaio1
  - libmysqlclient-dev
  - libnotify-bin
  - mysql-client
  - ntp
  - postgresql
  - silversearcher-ag
  - tcl
  - whois
  - zip 
brew_pkg:
  - ag
  - autoconf
  - automake
  - bash
  - bash-completion@2
  - curl
  - deno
  - gdbm
  - gettext
  - glow
  - gnu-tar
  - gnu-sed
  - hashicorp/tap/terraform-ls
  - imagemagick@6
  - libevent
  - libidn2
  - libpq
  - libunistring
  - libyaml
  - llvm
  - lz4
  - make
  - mysql-client@8.0
  - ncurses
  - openssl
  - pkg-config
  - popt
  - postgresql@15
  - pstree
  - readline
  - rsync
  - shared-mime-info
  - sqlite
  - telnet
  - terminal-notifier
  - terraform
  - tesseract
  - wget
  - watch
  - xxhash
  - xz
  - yq
  - zstd
config_files:
  - .agignore
  - .bashrc
  - .bash_aliases
  - .bash_profile
  - .gitignore
  - .inputrc
working_directory:
  - .aws
  - .dotnet/tools
  - bin
  - src

